/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DRADeviceFieldRefApplyConfiguration represents a declarative configuration of the DRADeviceFieldRef type for use
// with apply.
//
// DRADeviceFieldRef selects a DRA-resolved device attribute for a given claim+request.
type DRADeviceFieldRefApplyConfiguration struct {
	// ClaimName must match pod.spec.resourceClaims[].name.
	ClaimName *string `json:"claimName,omitempty"`
	// RequestName must match the corresponding ResourceClaim.spec.devices.requests[].name.
	RequestName *string `json:"requestName,omitempty"`
	// Attribute specifies which standardized attribute to expose.
	// Supported values (alpha): "pciAddress", "mdevUUID".
	Attribute *string `json:"attribute,omitempty"`
}

// DRADeviceFieldRefApplyConfiguration constructs a declarative configuration of the DRADeviceFieldRef type for use with
// apply.
func DRADeviceFieldRef() *DRADeviceFieldRefApplyConfiguration {
	return &DRADeviceFieldRefApplyConfiguration{}
}

// WithClaimName sets the ClaimName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimName field is set to the value of the last call.
func (b *DRADeviceFieldRefApplyConfiguration) WithClaimName(value string) *DRADeviceFieldRefApplyConfiguration {
	b.ClaimName = &value
	return b
}

// WithRequestName sets the RequestName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestName field is set to the value of the last call.
func (b *DRADeviceFieldRefApplyConfiguration) WithRequestName(value string) *DRADeviceFieldRefApplyConfiguration {
	b.RequestName = &value
	return b
}

// WithAttribute sets the Attribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attribute field is set to the value of the last call.
func (b *DRADeviceFieldRefApplyConfiguration) WithAttribute(value string) *DRADeviceFieldRefApplyConfiguration {
	b.Attribute = &value
	return b
}
